version: "3"
services:
#  composer:
#    restart: 'no'
#    container_name: TP_CTF_composer
#    image: composer/composer:latest
#    command: install
#    volumes:
#      - ./www/:/app

  php:
    build: './php/'
    container_name: TP_CTF_PHP
    networks:
      - backend
    volumes:
      - ./www/:/var/www/

  apache:
    build: './apache/'
    container_name: TP_CTF_apache
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8082:80"
    volumes:
      - ./www/:/var/www/

  mysql:
    image: mysql:5.6.40
    container_name: TP_CTF_mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=TP_CTF
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d

networks:
  frontend:
  backend:
